# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Task.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(567, 742)
        MainWindow.setStatusTip("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("/* === Shared === */\n"
"* {\n"
"    background-color: #333333;\n"
"    color: #BBBBBB;\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"\n"
"/* === QWidget === */\n"
"QWidget:window {\n"
"    background: #333333;\n"
"    color: #BBBBBB;\n"
"    font-family: \"Segoe UI\";\n"
"\n"
"}\n"
"\n"
"/* === QPushButton === */\n"
"QPushButton {\n"
"    border: 1px solid #4f4f4f;\n"
"    padding: 4px;\n"
"    min-width: 65px;\n"
"    min-height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"/* =================== */\n"
"QLineEdit, QListView, QTreeView, QTableView, QAbstractSpinBox {\n"
"    background-color: rgb(66, 66, 66);\n"
"    color: #000;\n"
"    border: 1px solid #555;\n"
"}\n"
"\n"
"QAbstractScrollArea, QLineEdit, QTextEdit, QAbstractSpinBox, QComboBox {\n"
"    border: 1px solid #555;\n"
"    color:rgb(200, 200, 200);\n"
"}\n"
"\n"
"/* === QHeaderView === */\n"
"QHeaderView::section {\n"
"    height: 20px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: rgb(55, 55, 55);\n"
"    border: 0;\n"
"    /*字体颜色*/\n"
"    color: rgb(200, 200, 200);\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QTableWidget{\n"
"    background: rgb(55, 55, 55);\n"
"    selection-background-color: rgb(77, 77, 77);\n"
"    font-family: \"Segoe UI\";\n"
"\n"
"}\n"
"")
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.PlatformMode_CB = QtWidgets.QComboBox(self.centralwidget)
        self.PlatformMode_CB.setMaximumSize(QtCore.QSize(60, 16777215))
        self.PlatformMode_CB.setObjectName("PlatformMode_CB")
        self.PlatformMode_CB.addItem("")
        self.PlatformMode_CB.addItem("")
        self.horizontalLayout_3.addWidget(self.PlatformMode_CB)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RBgroupBox_layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.RBgroupBox_layoutWidget.setObjectName("RBgroupBox_layoutWidget")
        self.RBGroupBox_horizontalLayout = QtWidgets.QHBoxLayout(self.RBgroupBox_layoutWidget)
        self.RBGroupBox_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.RBGroupBox_horizontalLayout.setObjectName("RBGroupBox_horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.RBGroupBox_horizontalLayout.addItem(spacerItem1)
        self.RBgroupBox = QtWidgets.QGroupBox(self.RBgroupBox_layoutWidget)
        self.RBgroupBox.setEnabled(True)
        self.RBgroupBox.setMinimumSize(QtCore.QSize(0, 22))
        self.RBgroupBox.setStyleSheet("    background-color: rgb(66, 66, 66);\n"
"\n"
" color: #BBBBBB;\n"
"    border: 1px solid rgb(66, 66, 66);\n"
"font-family: \"Segoe UI\";")
        self.RBgroupBox.setTitle("")
        self.RBgroupBox.setFlat(False)
        self.RBgroupBox.setObjectName("RBgroupBox")
        self.layoutWidget = QtWidgets.QWidget(self.RBgroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 281, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.grouprb_horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.grouprb_horizontalLayout.setContentsMargins(1, 0, 0, 0)
        self.grouprb_horizontalLayout.setObjectName("grouprb_horizontalLayout")
        self.Platform_Label = QtWidgets.QLabel(self.layoutWidget)
        self.Platform_Label.setObjectName("Platform_Label")
        self.grouprb_horizontalLayout.addWidget(self.Platform_Label)
        self.W2rb = QtWidgets.QRadioButton(self.layoutWidget)
        self.W2rb.setObjectName("W2rb")
        self.grouprb_horizontalLayout.addWidget(self.W2rb)
        self.W9rb = QtWidgets.QRadioButton(self.layoutWidget)
        self.W9rb.setObjectName("W9rb")
        self.grouprb_horizontalLayout.addWidget(self.W9rb)
        self.GPUrb = QtWidgets.QRadioButton(self.layoutWidget)
        self.GPUrb.setObjectName("GPUrb")
        self.grouprb_horizontalLayout.addWidget(self.GPUrb)
        self.RBGroupBox_horizontalLayout.addWidget(self.RBgroupBox)
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.RBGroupBox_horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.RBgroupBox_layoutWidget)
        self.RBgroupBox_layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.RBgroupBox_layoutWidget2.setObjectName("RBgroupBox_layoutWidget2")
        self.RBGroupBox_horizontalLayout2 = QtWidgets.QHBoxLayout(self.RBgroupBox_layoutWidget2)
        self.RBGroupBox_horizontalLayout2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.RBGroupBox_horizontalLayout2.setContentsMargins(0, 0, 0, 0)
        self.RBGroupBox_horizontalLayout2.setObjectName("RBGroupBox_horizontalLayout2")
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.RBGroupBox_horizontalLayout2.addItem(spacerItem3)
        self.RBgroupBox2 = QtWidgets.QGroupBox(self.RBgroupBox_layoutWidget2)
        self.RBgroupBox2.setEnabled(True)
        self.RBgroupBox2.setMinimumSize(QtCore.QSize(0, 22))
        self.RBgroupBox2.setStyleSheet("    background-color: rgb(66, 66, 66);\n"
"\n"
" color: #BBBBBB;\n"
"    border: 1px solid rgb(66, 66, 66);\n"
"font-family: \"Segoe UI\";")
        self.RBgroupBox2.setTitle("")
        self.RBgroupBox2.setFlat(False)
        self.RBgroupBox2.setObjectName("RBgroupBox2")
        self.layoutWidget_4 = QtWidgets.QWidget(self.RBgroupBox2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 0, 341, 21))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.grouprb_horizontalLayout2_2 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.grouprb_horizontalLayout2_2.setContentsMargins(1, 0, 0, 0)
        self.grouprb_horizontalLayout2_2.setObjectName("grouprb_horizontalLayout2_2")
        self.Platform_Label_c = QtWidgets.QLabel(self.layoutWidget_4)
        self.Platform_Label_c.setObjectName("Platform_Label_c")
        self.grouprb_horizontalLayout2_2.addWidget(self.Platform_Label_c)
        self.c_W2rb = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.c_W2rb.setObjectName("c_W2rb")
        self.grouprb_horizontalLayout2_2.addWidget(self.c_W2rb)
        self.c_W3rb = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.c_W3rb.setObjectName("c_W3rb")
        self.grouprb_horizontalLayout2_2.addWidget(self.c_W3rb)
        self.c_W4rb = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.c_W4rb.setObjectName("c_W4rb")
        self.grouprb_horizontalLayout2_2.addWidget(self.c_W4rb)
        self.c_W9rb = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.c_W9rb.setObjectName("c_W9rb")
        self.grouprb_horizontalLayout2_2.addWidget(self.c_W9rb)
        self.c_GPUrb = QtWidgets.QRadioButton(self.layoutWidget_4)
        self.c_GPUrb.setObjectName("c_GPUrb")
        self.grouprb_horizontalLayout2_2.addWidget(self.c_GPUrb)
        self.RBGroupBox_horizontalLayout2.addWidget(self.RBgroupBox2)
        spacerItem4 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.RBGroupBox_horizontalLayout2.addItem(spacerItem4)
        self.verticalLayout.addWidget(self.RBgroupBox_layoutWidget2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.ID_horizontalLayout = QtWidgets.QHBoxLayout()
        self.ID_horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.ID_horizontalLayout.setObjectName("ID_horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ID_horizontalLayout.addItem(spacerItem5)
        self.TaskID = QtWidgets.QLabel(self.centralwidget)
        self.TaskID.setMaximumSize(QtCore.QSize(50, 25))
        self.TaskID.setObjectName("TaskID")
        self.ID_horizontalLayout.addWidget(self.TaskID)
        self.TaskID_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.TaskID_lineEdit.setMinimumSize(QtCore.QSize(90, 0))
        self.TaskID_lineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.TaskID_lineEdit.setObjectName("TaskID_lineEdit")
        self.ID_horizontalLayout.addWidget(self.TaskID_lineEdit)
        self.UserID = QtWidgets.QLabel(self.centralwidget)
        self.UserID.setMaximumSize(QtCore.QSize(50, 25))
        self.UserID.setObjectName("UserID")
        self.ID_horizontalLayout.addWidget(self.UserID)
        self.UserID_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UserID_lineEdit.setMinimumSize(QtCore.QSize(90, 0))
        self.UserID_lineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.UserID_lineEdit.setObjectName("UserID_lineEdit")
        self.ID_horizontalLayout.addWidget(self.UserID_lineEdit)
        spacerItem6 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ID_horizontalLayout.addItem(spacerItem6)
        self.IPkey = QtWidgets.QPushButton(self.centralwidget)
        self.IPkey.setMaximumSize(QtCore.QSize(50, 25))
        self.IPkey.setObjectName("IPkey")
        self.ID_horizontalLayout.addWidget(self.IPkey)
        self.Get_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Get_Button.setMinimumSize(QtCore.QSize(75, 22))
        self.Get_Button.setMaximumSize(QtCore.QSize(60, 25))
        self.Get_Button.setObjectName("Get_Button")
        self.ID_horizontalLayout.addWidget(self.Get_Button)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.ID_horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.ID_horizontalLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.maya_horizontalLayout = QtWidgets.QHBoxLayout()
        self.maya_horizontalLayout.setContentsMargins(-1, 5, -1, -1)
        self.maya_horizontalLayout.setSpacing(6)
        self.maya_horizontalLayout.setObjectName("maya_horizontalLayout")
        self.Maya_label = QtWidgets.QLabel(self.centralwidget)
        self.Maya_label.setMinimumSize(QtCore.QSize(0, 25))
        self.Maya_label.setObjectName("Maya_label")
        self.maya_horizontalLayout.addWidget(self.Maya_label)
        self.Version_label = QtWidgets.QLabel(self.centralwidget)
        self.Version_label.setMinimumSize(QtCore.QSize(0, 25))
        self.Version_label.setObjectName("Version_label")
        self.maya_horizontalLayout.addWidget(self.Version_label)
        self.Version_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Version_lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.Version_lineEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Version_lineEdit.setText("")
        self.Version_lineEdit.setObjectName("Version_lineEdit")
        self.maya_horizontalLayout.addWidget(self.Version_lineEdit)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.maya_horizontalLayout.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.maya_horizontalLayout)
        self.Plugins_horizontalLayout = QtWidgets.QHBoxLayout()
        self.Plugins_horizontalLayout.setContentsMargins(-1, 5, -1, -1)
        self.Plugins_horizontalLayout.setObjectName("Plugins_horizontalLayout")
        self.Plugins_verticalLayout = QtWidgets.QVBoxLayout()
        self.Plugins_verticalLayout.setContentsMargins(-1, -1, 10, -1)
        self.Plugins_verticalLayout.setObjectName("Plugins_verticalLayout")
        self.Plugins_label = QtWidgets.QLabel(self.centralwidget)
        self.Plugins_label.setObjectName("Plugins_label")
        self.Plugins_verticalLayout.addWidget(self.Plugins_label)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Plugins_verticalLayout.addItem(spacerItem9)
        self.Plugins_horizontalLayout.addLayout(self.Plugins_verticalLayout)
        self.Plugins_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.Plugins_tableWidget.setStyleSheet("")
        self.Plugins_tableWidget.setObjectName("Plugins_tableWidget")
        self.Plugins_tableWidget.setColumnCount(2)
        self.Plugins_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Plugins_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Plugins_tableWidget.setHorizontalHeaderItem(1, item)
        self.Plugins_horizontalLayout.addWidget(self.Plugins_tableWidget)
        self.Plugins_verticalLayout2 = QtWidgets.QVBoxLayout()
        self.Plugins_verticalLayout2.setObjectName("Plugins_verticalLayout2")
        self.Plugins_add = QtWidgets.QPushButton(self.centralwidget)
        self.Plugins_add.setObjectName("Plugins_add")
        self.Plugins_verticalLayout2.addWidget(self.Plugins_add)
        self.Plugins_reduce = QtWidgets.QPushButton(self.centralwidget)
        self.Plugins_reduce.setObjectName("Plugins_reduce")
        self.Plugins_verticalLayout2.addWidget(self.Plugins_reduce)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Plugins_verticalLayout2.addItem(spacerItem10)
        self.Plugins_horizontalLayout.addLayout(self.Plugins_verticalLayout2)
        spacerItem11 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Plugins_horizontalLayout.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.Plugins_horizontalLayout)
        self.Mapping_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.Mapping_verticalLayout_2.setObjectName("Mapping_verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Mapping_verticalLayout = QtWidgets.QVBoxLayout()
        self.Mapping_verticalLayout.setObjectName("Mapping_verticalLayout")
        self.Mapping_label = QtWidgets.QLabel(self.centralwidget)
        self.Mapping_label.setObjectName("Mapping_label")
        self.Mapping_verticalLayout.addWidget(self.Mapping_label)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Mapping_verticalLayout.addItem(spacerItem12)
        self.horizontalLayout_2.addLayout(self.Mapping_verticalLayout)
        self.Mapping_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.Mapping_tableWidget.setObjectName("Mapping_tableWidget")
        self.Mapping_tableWidget.setColumnCount(2)
        self.Mapping_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Mapping_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Mapping_tableWidget.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_2.addWidget(self.Mapping_tableWidget)
        self.Mapping_verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem13 = QtWidgets.QSpacerItem(65, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem13)
        self.Mapping_add = QtWidgets.QPushButton(self.centralwidget)
        self.Mapping_add.setMinimumSize(QtCore.QSize(75, 22))
        self.Mapping_add.setMaximumSize(QtCore.QSize(40, 22))
        self.Mapping_add.setSizeIncrement(QtCore.QSize(0, 0))
        self.Mapping_add.setObjectName("Mapping_add")
        self.horizontalLayout.addWidget(self.Mapping_add)
        spacerItem14 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem14)
        self.Mapping_reduce = QtWidgets.QPushButton(self.centralwidget)
        self.Mapping_reduce.setEnabled(True)
        self.Mapping_reduce.setMinimumSize(QtCore.QSize(75, 22))
        self.Mapping_reduce.setMaximumSize(QtCore.QSize(40, 22))
        self.Mapping_reduce.setObjectName("Mapping_reduce")
        self.horizontalLayout.addWidget(self.Mapping_reduce)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.Mapping_netuse = QtWidgets.QPushButton(self.centralwidget)
        self.Mapping_netuse.setMinimumSize(QtCore.QSize(75, 22))
        self.Mapping_netuse.setSizeIncrement(QtCore.QSize(0, 0))
        self.Mapping_netuse.setBaseSize(QtCore.QSize(0, 0))
        self.Mapping_netuse.setObjectName("Mapping_netuse")
        self.horizontalLayout.addWidget(self.Mapping_netuse)
        self.Mapping_verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.Mapping_verticalLayout_2)
        self.path_horizontalLayout = QtWidgets.QHBoxLayout()
        self.path_horizontalLayout.setContentsMargins(-1, 5, -1, -1)
        self.path_horizontalLayout.setObjectName("path_horizontalLayout")
        self.Input_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Input_Button.setMinimumSize(QtCore.QSize(75, 22))
        self.Input_Button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Input_Button.setObjectName("Input_Button")
        self.path_horizontalLayout.addWidget(self.Input_Button)
        self.Output_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Output_Button.setMinimumSize(QtCore.QSize(75, 22))
        self.Output_Button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Output_Button.setObjectName("Output_Button")
        self.path_horizontalLayout.addWidget(self.Output_Button)
        self.Customfile_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Customfile_Button.setMinimumSize(QtCore.QSize(75, 22))
        self.Customfile_Button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Customfile_Button.setObjectName("Customfile_Button")
        self.path_horizontalLayout.addWidget(self.Customfile_Button)
        self.PreRender_Button = QtWidgets.QPushButton(self.centralwidget)
        self.PreRender_Button.setMinimumSize(QtCore.QSize(75, 22))
        self.PreRender_Button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.PreRender_Button.setObjectName("PreRender_Button")
        self.path_horizontalLayout.addWidget(self.PreRender_Button)
        self.verticalLayout_2.addLayout(self.path_horizontalLayout)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem16)
        self.TextCMD_horizontalLayout = QtWidgets.QHBoxLayout()
        self.TextCMD_horizontalLayout.setObjectName("TextCMD_horizontalLayout")
        spacerItem17 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.TextCMD_horizontalLayout.addItem(spacerItem17)
        self.TextCMD = QtWidgets.QTextEdit(self.centralwidget)
        self.TextCMD.setEnabled(True)
        self.TextCMD.setToolTipDuration(-1)
        self.TextCMD.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TextCMD.setLineWidth(1)
        self.TextCMD.setObjectName("TextCMD")
        self.TextCMD_horizontalLayout.addWidget(self.TextCMD)
        self.verticalLayout_2.addLayout(self.TextCMD_horizontalLayout)
        self.execute_horizontalLayout = QtWidgets.QHBoxLayout()
        self.execute_horizontalLayout.setContentsMargins(-1, 5, -1, -1)
        self.execute_horizontalLayout.setObjectName("execute_horizontalLayout")
        self.Maya_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Maya_Button.setMinimumSize(QtCore.QSize(75, 22))
        self.Maya_Button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Maya_Button.setObjectName("Maya_Button")
        self.execute_horizontalLayout.addWidget(self.Maya_Button)
        self.CMD_Button = QtWidgets.QPushButton(self.centralwidget)
        self.CMD_Button.setMinimumSize(QtCore.QSize(75, 22))
        self.CMD_Button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.CMD_Button.setObjectName("CMD_Button")
        self.execute_horizontalLayout.addWidget(self.CMD_Button)
        self.Close_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Close_Button.setMinimumSize(QtCore.QSize(75, 22))
        self.Close_Button.setMaximumSize(QtCore.QSize(120, 16777215))
        self.Close_Button.setObjectName("Close_Button")
        self.execute_horizontalLayout.addWidget(self.Close_Button)
        self.verticalLayout_2.addLayout(self.execute_horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 567, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PlatformMode_CB.setItemText(0, _translate("MainWindow", "China"))
        self.PlatformMode_CB.setItemText(1, _translate("MainWindow", "Fox"))
        self.Platform_Label.setText(_translate("MainWindow", "Platform"))
        self.W2rb.setText(_translate("MainWindow", "W2"))
        self.W9rb.setText(_translate("MainWindow", "W9"))
        self.GPUrb.setText(_translate("MainWindow", "GPU"))
        self.Platform_Label_c.setText(_translate("MainWindow", "Platform"))
        self.c_W2rb.setText(_translate("MainWindow", "W2"))
        self.c_W3rb.setText(_translate("MainWindow", "W3"))
        self.c_W4rb.setText(_translate("MainWindow", "W4"))
        self.c_W9rb.setText(_translate("MainWindow", "W9"))
        self.c_GPUrb.setText(_translate("MainWindow", "GPU"))
        self.TaskID.setText(_translate("MainWindow", "Task ID"))
        self.UserID.setText(_translate("MainWindow", "User ID"))
        self.IPkey.setText(_translate("MainWindow", "IP key"))
        self.Get_Button.setText(_translate("MainWindow", "Get"))
        self.Maya_label.setText(_translate("MainWindow", "  Maya    :"))
        self.Version_label.setText(_translate("MainWindow", "version "))
        self.Plugins_label.setText(_translate("MainWindow", " Plugins  :"))
        item = self.Plugins_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.Plugins_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Version"))
        self.Plugins_add.setText(_translate("MainWindow", "+"))
        self.Plugins_reduce.setText(_translate("MainWindow", "-"))
        self.Mapping_label.setText(_translate("MainWindow", " Mapping  :"))
        item = self.Mapping_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Drive"))
        item = self.Mapping_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Folder"))
        self.Mapping_add.setText(_translate("MainWindow", "+"))
        self.Mapping_reduce.setText(_translate("MainWindow", "-"))
        self.Mapping_netuse.setText(_translate("MainWindow", "net use"))
        self.Input_Button.setText(_translate("MainWindow", "Input"))
        self.Output_Button.setText(_translate("MainWindow", "Output"))
        self.Customfile_Button.setText(_translate("MainWindow", "Custom file"))
        self.PreRender_Button.setText(_translate("MainWindow", "PreRender"))
        self.Maya_Button.setText(_translate("MainWindow", "Maya"))
        self.CMD_Button.setText(_translate("MainWindow", "CMD"))
        self.Close_Button.setText(_translate("MainWindow", "Close"))

